import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.kotlin.plugin.serialization' version '2.3.0'
    id 'java-gradle-plugin'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(KotlinCompile).configureEach {
    kotlin {
        compilerOptions {
            jvmTarget = "17"
        }
    }
}

gradlePlugin {
    plugins {
        vegasPlugin {
            id = 'com.fitnow.vegas'
            implementationClass = 'com.fitnow.vegas.compiler.VegasPlugin'
        }
    }
}

dependencies {
    implementation gradleApi()
    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.3.0"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3"
    implementation project(':vegas-core')
}
